### PR TITLE
dc/237 encrypt large file

### PR DESCRIPTION
**Pull request by cdawei**
# Pull Request Details

## What issue does this PR address

- Encrypt chunks of large file and its representing `.ttl` file

- Link to associated issue: #237 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [x] Linux
  - [ ] MacOS
  - [x] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [x] Merge dev into the branch
- [x] Resolve any conflicts
- [x] Add one line summary into CHANGELOG.md
- [x] Bump appropriate version number in pubspec.yaml
- [x] Push to git repository and review
- [x] Merge PR into dev

### CODE REVIEW

**Comment by cdawei** [comment]
Please use the same test as shown in https://github.com/anusii/solidpod/issues/186

Note that:
- Chunks of the large file is now encrypted using AES, the encryption key and IV is stored in `exampleApp/data/large_file.bin.ttl`
- The content of `exampleApp/data/large_file.bin.ttl` is also encrypted, its encryption key and IV is stored in `exampleApp/encryption/ind-keys.ttl`

**Comment by anushkavidanage** [comment]
Error I am getting.

```
D/AndroidRuntime( 5479): Shutting down VM
E/AndroidRuntime( 5479): FATAL EXCEPTION: main
E/AndroidRuntime( 5479): Process: com.togaware.demopod, PID: 5479
E/AndroidRuntime( 5479): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=55226, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/... flg=0x43 }} to activity {com.togaware.demopod/com.togaware.demopod.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime( 5479): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5654)
E/AndroidRuntime( 5479): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5693)
E/AndroidRuntime( 5479): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime( 5479): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 5479): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/AndroidRuntime( 5479): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/AndroidRuntime( 5479): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2547)
E/AndroidRuntime( 5479): 	at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime( 5479): 	at android.os.Looper.loopOnce(Looper.java:242)
E/AndroidRuntime( 5479): 	at android.os.Looper.loop(Looper.java:362)
E/AndroidRuntime( 5479): 	at android.app.ActivityThread.main(ActivityThread.java:8393)
E/AndroidRuntime( 5479): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5479): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 5479): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
E/AndroidRuntime( 5479): Caused by: java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime( 5479): 	at java.io.FileOutputStream.write(FileOutputStream.java:384)
E/AndroidRuntime( 5479): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate.onActivityResult(FilePickerDelegate.java:96)
E/AndroidRuntime( 5479): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:774)
E/AndroidRuntime( 5479): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:422)
E/AndroidRuntime( 5479): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:964)
E/AndroidRuntime( 5479): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:911)
E/AndroidRuntime( 5479): 	at android.app.Activity.dispatchActivityResult(Activity.java:9086)
E/AndroidRuntime( 5479): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5647)
E/AndroidRuntime( 5479): 	... 13 more
I/Process ( 5479): Sending signal. PID: 5479 SIG: 9
```

**Comment by cdawei** [comment]
> Thanks Dawei. Works great in Windows. One thing I noticed is that for Android the download function does not work. Uploading and deleting works for Android. We might need another task to tackle this.

Thanks Anushka. I created a new issue https://github.com/anusii/solidpod/issues/239 for this task.

**Comment by cdawei** [comment]
> E/AndroidRuntime( 5479): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate.onActivityResult(FilePickerDelegate.java:96)

A similar issue was reported in the `flutter_file_picker` package github repository https://github.com/miguelpruivo/flutter_file_picker/issues/1604
It seems the issue has been fixed in version `8.1.3` and demopod was using `8.0.0+1`. 

I've just updated demopod to use the latest `flutter_file_picker` (version `8.1.5`). It would be great if @anushkavidanage could do another test on the android phone and see if the downloading works. Thanks.

**Comment by cdawei** [comment]
According to Anushka, when trying to built the demopod on Android, got the following error:
```
C:\Users\admin-u6482057\AppData\Local\Pub\Cache\hosted\pub.dev\file_picker-8.1.5\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:257: error: cannot find symbol        if (registrar != null) {            ^  symbol:   variable registrar  location: class FilePickerPluginC:\Users\admin-u6482057\AppData\Local\Pub\Cache\hosted\pub.dev\file_picker-8.1.5\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:260: error: cannot find symbol            registrar.addActivityResultListener(this.delegate);            ^  symbol:   variable registrar  location: class FilePickerPlugin2 errors
```

It seems someone has reported this on GitHub here https://github.com/miguelpruivo/flutter_file_picker/issues/1645
And a pull request to fix this issue is pending review by the `flutter_file_picker` package developers https://github.com/miguelpruivo/flutter_file_picker/issues/1643

**Review by gjwgit — APPROVED** [review]

**Comment by anushkavidanage** [comment]
Since we need to explore a bit more into this issue, I suggest we merge this, release a new version for `solidpod` and then work on this issue in another branch.

**Pull request merged**
