### PR TITLE
Kev/102_change_key_frontend

### PR DESCRIPTION
**Pull request by junhaow1**
# Pull Request Details

## What issue does this PR address

- implemented change key widget in keypod app (frontend)

- Link to associated issue: #102 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [x] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

### CODE REVIEW

**Comment by cdawei** [comment]
On the "back" button.

**Review by gjwgit — CHANGES_REQUESTED** [review]
Thanks @junhaow1. Functioanlity looks great.

Could we have ChangeSolidKeyDialog() exported from solidpod and in keypod I create a button in the test tab to call this ChangeSolidKeyDiaolog().

**Comment by junhaow1** [comment]
> Thanks @junhaow1. Functioanlity looks great.
> 
> Could we have ChangeSolidKeyDialog() exported from solidpod and in keypod I create a button in the test tab to call this ChangeSolidKeyDiaolog().

sounds good, on it

**Comment by junhaow1** [comment]
> Thanks @junhaow1. Functioanlity looks great.
> 
> Could we have ChangeSolidKeyDialog() exported from solidpod and in keypod I create a button in the test tab to call this ChangeSolidKeyDiaolog().

ready to be reviewed :)

**Review by cdawei — APPROVED** [review]

**Review by gjwgit — CHANGES_REQUESTED** [review]
Am I doing something wrong?

Do I need to be logged in first, before I can change my key? Or is this all local?

Currently I start the app, click CONTINUE, click CHANGE KEY and it goes straight into the change key popup.

I then type any rubbish and it seems to accept it, irrespective of my old key (but then how does it know who I am), and seems to return without complaint?

I think on the popup page it also needs to show me the current WebID. 

I suspect I need to be logged in to change the key.

**Comment by junhaow1** [comment]
> Am I doing something wrong?
> 
> Do I need to be logged in first, before I can change my key? Or is this all local?
> 
> Currently I start the app, click CONTINUE, click CHANGE KEY and it goes straight into the change key popup.
> 
> I then type any rubbish and it seems to accept it, irrespective of my old key (but then how does it know who I am), and seems to return without complaint?
> 
> I think on the popup page it also needs to show me the current WebID.
> 
> I suspect I need to be logged in to change the key.

Hi @gjwgit  we have another backend ticket to deal with  what you mentioned. This PR is just for the frontend part.

**Comment by gjwgit** [comment]
Also, I logged in, then changed my security key but it did not seem to get changed? I had to use my old one again.

**Comment by gjwgit** [comment]
Also, As an App developer, how do I do this with an icon rather than a button?

**Comment by gjwgit** [comment]
Not fully tested but let's get it in  to dev asap.

**Review by gjwgit — APPROVED** [review]

**Pull request merged**
