### PR TITLE
kev/82_button_min_height

### PR DESCRIPTION
**Pull request by junhaow1**
# Pull Request Details

## What issue does this PR address

- increase the button heights on the login screen

- Link to associated issue: #82 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [x] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [x] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

### CODE REVIEW

**Review by gjwgit — COMMENTED** [review]
Not sure if related but I am now seeing with dev keypod and this solidpod branch:

```
flutter run --device-id linux
Launching lib/main.dart on Linux in debug mode...
ERROR: solidpod/lib/src/solid/api/rest_api.dart:825:31: Error: No named parameter with the name 'forceRefresh'.
ERROR:             .getTokenResponse(forceRefresh: true, dPoPToken: dPopToken);
ERROR:                               ^^^^^^^^^^^^
ERROR: Target kernel_snapshot failed: Exception
Building Linux application...                                           
Error: Build process failed
```

**Comment by junhaow1** [comment]
> Not sure if related but I am now seeing with dev keypod and this solidpod branch:
> 
> ```
> flutter run --device-id linux
> Launching lib/main.dart on Linux in debug mode...
> ERROR: solidpod/lib/src/solid/api/rest_api.dart:825:31: Error: No named parameter with the name 'forceRefresh'.
> ERROR:             .getTokenResponse(forceRefresh: true, dPoPToken: dPopToken);
> ERROR:                               ^^^^^^^^^^^^
> ERROR: Target kernel_snapshot failed: Exception
> Building Linux application...                                           
> Error: Build process failed
> ```

same for me, after doing "flutter pub get" in keypod repo, this error disappeared.

**Comment by cdawei** [comment]
The `forceRefresh` argument became a named parameter in `solid-auth-0.1.17`, a `flutter pub get` (possibly also with `flutter clean`) might help resolve it.

**Review by gjwgit — APPROVED** [review]
Tested on linux.

**Review by cdawei — APPROVED** [review]

**Pull request merged**
