### PR TITLE
Av/216 solidpod release v0.6.0

### PR DESCRIPTION
**Pull request by anushkavidanage**
# Pull Request Details

## What issue does this PR address

- Solidpod release 0.6.0

- Link to associated issue: https://github.com/anusii/solidpod/issues/216

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [x] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [x] Windows
- [ ] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

### CODE REVIEW

**Review by cdawei — APPROVED** [review]
Changes look good, demopod worked as expected in my test. Thanks Anushka.

**Comment by cdawei** [comment]
I've tested the branch `av/216_solidpod_release_v1.0.0` using the solid server (v7.1.0) on `dev.empwr.au`. Most of the functions of `demopod` worked, and the `Login` button respects the server url manullay specified (e.g., `solid.dev.empwr.au`).

However, if I click `Forget Remote Server Login` and then `Show Pod Data File`, the popup login still uses `pods.solidcommunity.au` (which is the default server) as shown below. Do we need an UI element for users to specify the solid server url for popup login?

image

**Comment by srodriguez142857** [comment]
Please check the following screen recordings:  

- [Screen Recording 2024-08-07 175602](https://cloud.empwr.au/index.php/apps/maps/s/BWEAxXzsW72Bbrz).
The "Success" message at the end is misleading. It shouldn't be displayed, right? This is a minor behaviour.  

- [Screen Recording 2024-08-07 180710](https://cloud.empwr.au/index.php/apps/maps/s/KmcTCZpgpNeeJBP).  The app presents the "Loading" message but doesn't perform anything.  Should all those functions be available even if the user hasn't logged in?
Apologies for the background music... 🤓

**Comment by srodriguez142857** [comment]
I have the following observations/comments:

- When I click the "Login" button, nothing happens. This was my first time accessing this function.  
[Screen Recording 2024-08-08 155057](https://cloud.empwr.au/index.php/s/NcCnwAKNz8ibABW).  

- Similarly, nothing happens when clicking the "Create pod" button.  
[Screen Recording 2024-08-08 155411](https://cloud.empwr.au/index.php/s/GQPytAzqaAAGkDY).  

- "**Create client credentials token**":  A button should be included to easily copy the token ID and token secret keys to the clipboard, so the user can easily copy them:  
Screenshot 2024-08-08 160123

- At the beginning, it displays the following.  It didn't make sense. It should show a proper message when this happens.  
Screenshot 2024-08-08 154727

- A typo in the following message:  
image

I still haven't gone over all the features.  The observations/comments are mild.  If critical, I can approve, and we can merge the changes.  Also, we can have a short session where I test the app with Anushka or Dawei and check the behaviours.  As a new user, I might do things differently... 🙂

**Comment by anushkavidanage** [comment]
Thanks Sergio. All of the above are related to the server side which we usually do not touch. We take the CSS as it is and deploy it. With that being said, I am not sure why you are getting the first two issues. I am able to create a POD in pods.solidcommunity.au without facing those.

**Comment by srodriguez142857** [comment]
Please check the following screen recordings:  

- [Screen Recording 2024-08-14 201836](https://cloud.empwr.au/index.php/s/cqA93jPSpJ7fMAE).
It throws an exception (null check operator) after the registration phase.  The log from the terminal is [here](https://cloud.empwr.au/index.php/s/gWWN8eDS5L8Zd6i).

- [Screen Recording 2024-08-14 202908](https://cloud.empwr.au/index.php/s/pRgYSPPGPZmzqPA).  The `Date` and `webID` data should be refreshed when clicking the "back" button/arrow after "forgetting the login".

**Comment by srodriguez142857** [comment]
All good, @anushkavidanage.  Removing the "back arrow" was clever. 
The app works well, and no issues were raised on the server side during my testing.
I will approve the review.

**Review by srodriguez142857 — APPROVED** [review]

**Pull request merged**
