### PR TITLE
Kev/65&63&66_warning_popup

### PR DESCRIPTION
**Pull request by junhaow1**
# Pull Request Details

## What issue does this PR address

- removed the popup warning for checkbutton
 request password key first, then submit button, then resources created
 Password entry will not be lost if the checkbox is not selected

- Link to associated issue: #65 
- #63 
- #66 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep`)
- [x] Pre-exisiting lint errors noted: 
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [x] Chrome
  - [ ] iOS
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added 2 reviewers

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [x] Merge dev into the branch
- [x] Resolve any conflicts
- [x] Bump appropriate version and build number in pubspec.yaml
- [x] Add one line summary into CHANGELOG.md
- [ ] Push to git repository and review
- [x] Merge PR into dev

### CODE REVIEW

**Comment by cdawei** [comment]
The changes look good. Two minor comments:
- The alter text looks a little too big
alter

- I guess we don't need to repeat the common text in the URLs
names

**Comment by junhaow1** [comment]
> The changes look good. Two minor comments:
> 
> * The alter text looks a little too big
>   alter
> * I guess we don't need to repeat the common text in the URLs
>   names

On it

**Comment by gjwgit** [comment]
> > The changes look good. Two minor comments:
> > 
> > * The alter text looks a little too big
> >   alter
> > * I guess we don't need to repeat the common text in the URLs
> >   names
> 
> On it

For the list of resources, have the base of the URI once in the heading:

`Resources that will be created within https://pods.solidcommunity.au/joe-demo/keypod:`

And then list

```
sharing
shared
data
...
```

**Comment by gjwgit** [comment]
I have also made some format and layout changes.

**Review by gjwgit — APPROVED** [review]

**Comment by gjwgit** [comment]
Hold the PR until we have the change suggested by @cdawei: show the URI base path just once.

**Pull request merged**
