### PR TITLE
dc/117 refactor pod init

### PR DESCRIPTION
**Pull request by cdawei**
# Pull Request Details

## What issue does this PR address

- Refactor POD initialisation code to reuse existing functions + minor UI tweak.

- Link to associated issue: #117 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [x] Linux
  - [ ] MacOS
  - [ ] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [x] Merge dev into the branch
- [x] Resolve any conflicts
- [x] Add one line summary into CHANGELOG.md
- [x] Bump appropriate version number in pubspec.yaml
- [x] Push to git repository and review
- [x] Merge PR into dev

### CODE REVIEW

**Comment by cdawei** [comment]
This pull request is an attempt to refactor the current POD initialisation code to make use of existing key/auth/rdf utility functions.
The POD initialisation procedure in keypod with this PR worked as before in my test, please test if the initialisation procedure in keypod also works as before for you. Thanks.

**Review by gjwgit — CHANGES_REQUESTED** [review]
Not working for me - With dev keypod and dev solid pod I click CONTINUE and then see my data. But with solidpod branch dc/117 It crashes:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
#0      AuthDataManager._loadData (package:solidpod/src/solid/utils/authdata_manager.dart:245:34)
<asynchronous suspension>
#1      AuthDataManager.getWebId (package:solidpod/src/solid/utils/authdata_manager.dart:207:22)
<asynchronous suspension>
#2      checkLoggedIn (package:solidpod/src/solid/utils/misc.dart:193:17)
<asynchronous suspension>
#3      loginIfRequired (package:solidpod/src/solid/common_func.dart:46:20)
<asynchronous suspension>
#4      readPod (package:solidpod/src/solid/read_pod.dart:54:3)
<asynchronous suspension>
#5      _HomeScreenState._writePrivateData (package:keypod/screens/home_page.dart:119:27)
<asynchronous suspension>
```

**Review by gjwgit — APPROVED** [review]

**Review by gjwgit — CHANGES_REQUESTED** [review]
Currently I still loop back to the initial setup page after a submit. The keypod setup on the server seems to work but I get random folders there as well

image

**Comment by cdawei** [comment]
> Currently I still loop back to the initial setup page after a submit.

This is a temporary fix in keypod https://github.com/anusii/keypod/pull/100 but a systematic fix in `solidpod` is required by resolving #157 as we have seen a similar issue before https://github.com/anusii/keypod/issues/72

> The keypod setup on the server seems to work but I get random folders there as well. 

It would be interesting to know the steps that triggers the random folders. I am unable to reproduce the problem so far.

> I think this is a long standing issue and could do with your look at it to see if you can resolve this problem.

Agreed, #157 is created for this investigation.

**Comment by cdawei** [comment]
Regarding the random folders, Kevin mentioned that it is due to create a folder which already exists. 

The current POD initialisation code does check which folders/files exist and create only the missing ones. I will double check those functions.

**Review by gjwgit — APPROVED** [review]

**Review by junhaow1 — APPROVED** [review]

**Pull request merged**
